#pragma checksum "MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "594816371914079D6E823E45971AE9DF0ADA1548"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FittingBeamByFace;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FittingBeamByFace {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 27 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK06_1;
        
        #line default
        #line hidden
        
        
        #line 33 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK06_2;
        
        #line default
        #line hidden
        
        
        #line 39 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK06_3;
        
        #line default
        #line hidden
        
        
        #line 52 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ProfileText;
        
        #line default
        #line hidden
        
        
        #line 55 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK07_1;
        
        #line default
        #line hidden
        
        
        #line 63 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK07_2;
        
        #line default
        #line hidden
        
        
        #line 71 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK07_3;
        
        #line default
        #line hidden
        
        
        #line 82 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK08_1;
        
        #line default
        #line hidden
        
        
        #line 88 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK08_2;
        
        #line default
        #line hidden
        
        
        #line 99 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK09_1;
        
        #line default
        #line hidden
        
        
        #line 105 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK09_2;
        
        #line default
        #line hidden
        
        
        #line 111 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK09_3;
        
        #line default
        #line hidden
        
        
        #line 117 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK09_4;
        
        #line default
        #line hidden
        
        
        #line 133 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK10_1;
        
        #line default
        #line hidden
        
        
        #line 139 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK10_2;
        
        #line default
        #line hidden
        
        
        #line 145 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK10_3;
        
        #line default
        #line hidden
        
        
        #line 151 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CK10_4;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FittingBeamByFace;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 25 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK06_Peak2Points_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CK06_1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            
            #line 31 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK06_PickPart_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CK06_2 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            
            #line 37 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK06_Global_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.CK06_3 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            
            #line 50 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK07_Peak2Points_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ProfileText = ((System.Windows.Controls.TextBox)(target));
            
            #line 53 "MainWindow.xaml"
            this.ProfileText.KeyDown += new System.Windows.Input.KeyEventHandler(this.InputProfile);
            
            #line default
            #line hidden
            return;
            case 9:
            this.CK07_1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            
            #line 61 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK07_Column_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.CK07_2 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            
            #line 70 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK07_Polibeam_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.CK07_3 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            
            #line 80 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK08_CreatePlate_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.CK08_1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            
            #line 87 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK08_SetWorkPlane_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.CK08_2 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            
            #line 97 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK09_SetWorkplane_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.CK09_1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            
            #line 104 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK09_ApplyFitting_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.CK09_2 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            
            #line 110 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK09_PartCut_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.CK09_3 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            
            #line 116 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK09_PolygonCut_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.CK09_4 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 26:
            
            #line 128 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK10_Bolt_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 130 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK10_SetWorkPlane_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.CK10_1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            
            #line 138 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_C10_Weld_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.CK10_2 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            
            #line 144 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK10_AddTo_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.CK10_3 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            
            #line 150 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_CK09_PolygonCut_Click);
            
            #line default
            #line hidden
            return;
            case 34:
            this.CK10_4 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            
            #line 157 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Go_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            
            #line 166 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_W36_CheckCrossBeam);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

